---
## GLOBAL SETTINGS ##
aws_customer_name: customer
aws_environment: stage
aws_region: eu-central-1
aws_writer_zone: "{{ aws_region }}a"
aws_reader_zone: "{{ aws_region }}b"
aws_writer_tags: "{{ rds_writer_instance_name }}"
aws_reader_tags: "{{ rds_reader_instance_name }}"
aws_parameter_group_prefix: "{{ safeboda }}"
aws_parameter_group_version: 57

## CLUSTER SETTINGS ##
aurora_cluster_name: "{{ aws_customer_name }}-{{ aws_environment }}-rds"
#use "aurora" for mysql56 compatible or "aurora-mysql" for 5.7 compatible
aurora_cluster_engine: aurora-mysql
aurora_cluster_engine_version: 5.7.12
aurora_cluster_port: 3306
aurora_cluster_backup_retention: 5
aurora_cluster_backup_window:
aurora_cluster_parameters_group: "{{ aws_parameter_group_prefix }}-cluster-{{ aws_parameter_group_version }}"
aurora_cluster_security_group:
aurora_cluster_subnet_group: "{{ aws_customer_name }}-{{ aws_environment }}"
aurora_cluster_encryption: true
aurora_cluster_tags:
aurora_cluster_availability_zones:
  - "{{ aws_region }}a"
  - "{{ aws_region }}b"
  - "{{ aws_region }}c"
aurora_cluster_username: "{{ aws_customer_name }}-{{ aws_environment }}_user"
aurora_cluster_password: #encrypt password using ansible-vault encrypt_string

## INSTANCE SETTINGS ##
rds_writer_instance_name: "{{ aws_customer_name }}-{{ aws_environment }}-writer"
rds_reader_instance_name: "{{ aws_customer_name }}-{{ aws_environment }}-reader"
rds_instance_type: db.t2.micro
rds_version_upgrade: no
rds_cluster_maint_window:
rds_parameters_group: "{{ aws_parameter_group_prefix }}-{{ aws_parameter_group_version }}"

rds_instance_subnet_group: "{{ aurora_cluster_subnet_group }}"
rds_security_groups:
rds_publicly_accessible: false

rds_instance_default_tags:
  environment: "{{ aws_region }}"
  customer: "{{ aws_customer_name }}"
rds_writer_instance_tags: "{{ rds_instance_default_tags | combine(aws_writer_tags) }}"
rds_reader_instance_tags: "{{ rds_instance_default_tags | combine(aws_reader_tags) }}"

## DB SETTINGS ##
# if this parameter is not specified, no database is created in the DB instance.
db_name: 
