---
- block:
  - name: Ensure the VM is updated
    yum:
      name: '*'
      state: latest
    delegate_to: "{{ item.public_dns_name }}"
    with_items: "{{ ec2.tagged_instances }}"
  
  - name: Ensure docker is installed
    yum:
      pkg: docker
      state: latest
    delegate_to: "{{ item.public_dns_name }}"
    with_items: "{{ ec2.tagged_instances }}"
  
  - name: Ensure python-pip is installed
    yum:
      pkg: python-pip
      state: latest
    delegate_to: "{{ item.public_dns_name }}"
    with_items: "{{ ec2.tagged_instances }}"
  
  - name: Ensure docker-py is installed
    pip:
      name: docker-py
    delegate_to: "{{ item.public_dns_name }}"
    with_items: "{{ ec2.tagged_instances }}"
  
  - name: Add ec2-user to docker group
    user:
      name: ec2-user
      group: docker
    delegate_to: "{{ item.public_dns_name }}"
    with_items: "{{ ec2.tagged_instances }}"
  
  - name: Ensure docker is started
    systemd:
      name: docker
      state: started
      enabled: yes
    delegate_to: "{{ item.public_dns_name }}"
    with_items: "{{ ec2.tagged_instances }}"

  remote_user: ec2-user
  become: true
